Contributor list displayed in card
FCCVienna/FCCVienna.github.io pull request #49
Opened 2017-10-11 20:30 UTC by SoumyadeepJana

2017-10-12 12:09 UTC, DDCreationStudios commented
Hi @SoumyadeepJana ! Thanks a lot! Looks great! Maybe we can choose a light green color instead of the blue? 

@robeerob  What are your thoughts? Please do not merge since we overwrite the previous contributors list. 

Next step would be to apply the stylings to all contributors 🚀

2017-10-12 13:58 UTC, SoumyadeepJana commented
Yes sure

On 12 Oct 2017 5:40 p.m., "Daniel Deutsch" <notifications@github.com> wrote:

> Hi @SoumyadeepJana <https://github.com/soumyadeepjana> ! Thanks a lot!
> Looks great! Maybe we can choose a light green color instead of the blue?
>
> @robeerob <https://github.com/robeerob> What are your thoughts? Please do
> not merge since we overwrite the previous contributors list.
>
> Next step would be to apply the stylings to all contributors 🚀
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/FCCVienna/FCCVienna.github.io/pull/49#issuecomment-336110881>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/APUgQYGZNapnur7XjagG-KXABqBbtgABks5srgGYgaJpZM4P2FOG>
> .
>

2017-10-12 20:30 UTC, robaxelsen approved these changes

2017-10-12 20:33 UTC, robeerob commented
@DDCreationStudios Sorry, I goofed! Approved wrong review (meant to approve #50, but was in wrong browser tab). Please ignore my review for now. Will review and leave comment once actually reviewed.

2017-10-12 20:43 UTC, robeerob commented
@SoumyadeepJana Overall I like the work you've put into this PR very much. Thanks for taking the time and energy to present this to us. I would suggest to change color, as @DDCreationStudios also suggested, to a green that is harmonizing better with the existing color palette. Would also suggest to change the color of the <hr> used in the cards.

@DDCreationStudios I have two concerns. One is that this conflicts with issue #36 that @himanshuc3 is working on, and the second is that if we implement this we also need a version without contributor picture or with "dummy"/standard picture/graphic for the ones that haven't provides us with any (or do not have a GitHub picture to link to). What do you think?

2017-10-15 15:52 UTC, DDCreationStudios commented
@robeerob We can simply resolve conflicts the normal way when merging. And I will add dummy pictures when necessary, but I would vote for improving the display this way. We can improve the PR afterwards all the time. Let's keep the inovation and ideas going :)

2017-10-16 18:20 UTC, Createdd requested changes
Thanks! Can you take a look at my remarks? :)

2017-10-16 18:20 UTC, DDCreationStudios commented on index.html
> +
can you keep the contributors list and just add one card as an example? Or grant me write access to your fork, so I can push my commits to your branch and merge it?

2017-10-16 18:20 UTC, DDCreationStudios commented on index.html
> +      <div class="row">
Example code to copy:

```html
<!DOCTYPE html>
<html lang="en">

<head>
  <title>FreeCodeCamp Vienna</title>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <link rel="shortcut icon" type="image/x-icon" href="favicon.ico" />
  <link rel="icon" type="image/x-icon" href="favicon.ico" />
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.1/css/materialize.min.css">
  <link rel="stylesheet" href="./styles.css">
  <link href="https://fonts.googleapis.com/css?family=Varela+Round" rel="stylesheet">
 

</head>

<body>

  <div class="navbar-fixed">
    <nav>
      <div class="nav-wrapper teal">
        <a href="#" class="brand-logo">FreeCodeCampVienna</a>
        <ul id="nav-mobile" class="right hide-on-med-and-down">
          <li><a href="https://www.meetup.com/de-DE/Free-Code-Camp-Vienna/"><i class="fa fa-meetup material-icons" aria-hidden="true"></i></a></li>
          <li><a href="https://github.com/FCCVienna/FCCVienna"><i class="fa fa-github material-icons" aria-hidden="true"></i></a></li>
          <li><a href="https://www.facebook.com/groups/free.code.camp.vienna.austria"><i class="fa fa-facebook material-icons" aria-hidden="true"></i></a></li>
          <li><a href="https://twitter.com/freecodecampvie"><i class="fa fa-twitter material-icons" aria-hidden="true"></i></a></li>
        </ul>
      </div>
    </nav>
  </div>


  <div class="parallax-container" id="steinbauer1">
    <div class="parallax"><img src="https://images.unsplash.com/photo-1466656528034-6b43e26d9834?dpr=2&auto=format&fit=crop&w=1080&h=268&q=80&cs=tinysrgb&crop=" onerror="brokenImage('./images/steinbauer1ultra.jpg','steinbauer1')" alt="Background picture showing a view of Vienna"
      /></div>
  </div>
  <div id="steinbauer1new" style="display:none"></div>

  <div class="section teal">
    <div class="row container center">
      <h5>The official local group of</h5>
      <h3><a href="https://www.freecodecamp.org/" class="teal-text text-darken-4">FreeCodeCamp</a></h3>
      <h5>in Vienna, Austria</h5>
      <img src="./images/austriaflag.png" alt="Flag of Austria" height=100em />
    </div>
  </div>

  <div class="section teal">
    <div class="row center">
      <div class="row">
        <div class="col s12 m4">
          <div class="card teal darken-4">
            <div class="card-content white-text">
              <span class="card-title">Shared Values</span>
              <h2><i class="fa fa-free-code-camp large" aria-hidden="true"></i></h2>
              <p>We completely share the values and ideas of the FreeCodeCamp platform.</p>
            </div>
            <div class="section card-hover">
              <a href="https://www.freecodecamp.org/" target="_blank">FreeCodeCamp.org</a> is a place, where you can learn how to code - for free
            </div>
          </div>
        </div>
        <div class="col s12 m4">
          <div class="card teal darken-4">
            <div class="card-content white-text">
              <span class="card-title">Exchange</span>
              <h2><i class="fa fa-connectdevelop large" aria-hidden="true"></i></h2>
              <p>We connect developers and help beginners. We get people into coding.</p>
            </div>
            <div class="section card-hover">Get in touch with us on <a href="https://www.facebook.com/groups/free.code.camp.vienna.austria">Facebook</a> or <a href="https://twitter.com/freecodecampvie">Twitter</a>
            </div>
          </div>
        </div>
        <div class="col s12 m4">
          <div class="card teal darken-4">
            <div class="card-content white-text">
              <span class="card-title">Events</span>
              <h2><i class="fa fa-calendar large" aria-hidden="true"></i></h2>
              <p>We organize events, talks, coding sessions and just have fun. :) </p>
            </div>
            <div class="section card-hover">See our next event on <a href="https://www.meetup.com/de-DE/Free-Code-Camp-Vienna/" target="_blank">meetup</a>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>


  <div class="parallax-container">
    <div class="parallax"><img src="https://secure.meetupstatic.com/photos/event/6/d/e/d/highres_462628141.jpeg" alt="Background picture showing FreeCodeCampers at a meetup" /></div>
  </div>

  <div class="section teal darken-1">
    <div class="container row">
      <div class="col s12 m4">
        <h3 class="center">Goals</h3>
        <p>Connecting people with similar ambitions in real life and provide a platform for exchange and improvement. Everybody with an interest in coding is welcome. We are leading the local FCC Group in Vienna and provide monthly meetups for members.</p>
      </div>
      <div class="col s12 m8">
        <h3 class="center">Program</h3>
        <div class="row">
          <div class="col s12 m6">
            <dl>
              <dt>Showcase</dt>
              <dd> A person guiding the audience through a codebase they are currently working on.</dd>
              <dt>Discussion Circle</dt>
              <dd> Setting different topics and letting the audience discuss.</dd>
            </dl>
          </div>
          <div class="col s12 m6">
            <dl><dt>Presentations and Talks</dt>
              <dd> Different topics with following QA</dd>
              <dt>Coding Sessions</dt>
              <dd> Mob Sessions</dd>
              <dd> FCC Algorithms</dd>
              <dd> Other small Algorithms</dd>
            </dl>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="section teal">
    <div class="container row">
      <div class="col s12 m12 center">
        <h3>Sponsors</h3>
        <p>We are always looking for sponsors to cover free drinks and food, or the space where we can host our meetups! </br><a class="teal-text text-darken-4" href="#about">Get
          in contact with one of the organizers to discuss further details.</a></p>
      </div>
    </div>
    <div class="container row" style="padding: 20px 0;">
      <div class="col s12 m3"><a class="sponsor-logo" href="http://www.sektor5.at/">
          <img class="center-block" src="./images/sektor5-logo.png" alt="sektor5">
        </a></div>
      <div class="col s12 m3"><a class="sponsor-logo" href="http://www.stockwerk.co.at/">
          <img class="center-block" src="./images/stockwerk-logo.png" alt="Stockwerk">
        </a></div>
      <div class="col s12 m3"><a class="sponsor-logo" href="http://kivu.tech/"><img class="center-block" src="./images/kivu-logo.png" alt="KIVU"></a></div>
      <div class="col s12 m3"><a class="sponsor-logo" href="http://101.at/"><img class="center-block" src="./images/101-logo.png" alt="101CodingDesign"></a></div>

    </div>
  </div>


  <div class="section teal darken-1">
    <div class="container row">
      <h3 class="center">Our work reflected in numbers</h3>
      <div class="section">
        <img src="https://github.com/FCCVienna/FCCVienna.github.io/blob/master/images/meetupStats.png?raw=true" class="responsive-img z-depth-5" />
      </div>
      <ul id="staggeredList">
        <li class="section center section">
          <h4>Founded:</h4>
          <p>November 13th 2015</p>
        </li>
        <li class="section center">
          <h4>Currently:</h4>
          <p>More than 700 meetup.com members</p>
          <p>More than 550 facebook members</p>
          <p>More than 150 twitter followers</p>
        </li>
        <li class="section center">
          <h4>Contributed on Open Source:</h4>
          <p>More than 150 Github commits</p>
        </li>
        <li class="section center">
          <h4>Events organized:</h4>
          <p>22</p>
        </li>
        <li class="section center">
          <h4>Number of people helped out</h4>
          <p>A lot </p>
        </li>
      </u [...]

2017-10-21 14:22 UTC, calmandniceperson commented
@DDCreationStudios Since you mentioned changing the color of the cards, I'd recommend a light grey like this:
**Hex**: #F0F0F0
 **RGBA**(240, 240, 240, 1)
**HSL**(0, 0%, 94%)
**CMYB**(0%, 0%, 0%, 6%)

![screenshot-2017-10-21 at 16 20 17](https://user-images.githubusercontent.com/5265630/31852655-bb65b70c-b67b-11e7-8415-0a94f67dd561.png)

It's what Android apps use as the default background color. I think it somewhat draws the user's attention to the card (because the rest of the website is green, a very light grey sticks out) while also being easy on the eyes.

2017-11-14 13:04 UTC, DDCreationStudios commented
@robeerob Should we close this due to inactivity? I think the idea is nice, but we can also leave it as it is :)

2017-11-14 13:18 UTC, robeerob commented
@DDCreationStudios Sure, please close.

On Tue, Nov 14, 2017, 14:04 Daniel Deutsch <notifications@github.com> wrote:

> @robeerob <https://github.com/robeerob> Should we close this due to
> inactivity? I think the idea is nice, but we can also leave it as it is :)
>
> —
> You are receiving this because you were mentioned.
>
>
> Reply to this email directly, view it on GitHub
> <https://github.com/FCCVienna/FCCVienna.github.io/pull/49#issuecomment-344252615>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AMhkY1_yiuqZS7ovnb4jsrpCuxVm_iFdks5s2Y_AgaJpZM4P2FOG>
> .
>

2017-11-14 13:22 UTC, closed without merging